// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvf2yVMHHoLiqPsTvogGqtHo6Yyn_s7g',
    appId: '1:881181438902:web:484614192020c002750717',
    messagingSenderId: '881181438902',
    projectId: 'fir-5a3b5',
    authDomain: 'fir-5a3b5.firebaseapp.com',
    storageBucket: 'fir-5a3b5.appspot.com',
    measurementId: 'G-SSY94B9X6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVl_SKfbA_43ZrO2lp4w4Fxny61sNJrrs',
    appId: '1:881181438902:android:5ed9c2841460ab08750717',
    messagingSenderId: '881181438902',
    projectId: 'fir-5a3b5',
    storageBucket: 'fir-5a3b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYYYqove4OUK9SkXRjbrkI1WEaEp4t52w',
    appId: '1:881181438902:ios:e50bae9174fc45c4750717',
    messagingSenderId: '881181438902',
    projectId: 'fir-5a3b5',
    storageBucket: 'fir-5a3b5.appspot.com',
    iosBundleId: 'com.example.firebaseTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYYYqove4OUK9SkXRjbrkI1WEaEp4t52w',
    appId: '1:881181438902:ios:e50bae9174fc45c4750717',
    messagingSenderId: '881181438902',
    projectId: 'fir-5a3b5',
    storageBucket: 'fir-5a3b5.appspot.com',
    iosBundleId: 'com.example.firebaseTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvf2yVMHHoLiqPsTvogGqtHo6Yyn_s7g',
    appId: '1:881181438902:web:c8d597e279351c1b750717',
    messagingSenderId: '881181438902',
    projectId: 'fir-5a3b5',
    authDomain: 'fir-5a3b5.firebaseapp.com',
    storageBucket: 'fir-5a3b5.appspot.com',
    measurementId: 'G-XJ3VPJCS32',
  );
}
